// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EjhDrt7EUNTrueeIhGhGz7Md0t8kDAE',
    appId: '1:1038997808447:web:81d4aae1cb7a6f73e61f8a',
    messagingSenderId: '1038997808447',
    projectId: 'venture-vault-4f892',
    authDomain: 'venture-vault-4f892.firebaseapp.com',
    storageBucket: 'venture-vault-4f892.firebasestorage.app',
    measurementId: 'G-3DPKPJHS00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbo9BROuaSwPTfVBMbu1QC0lPwJ9kCV4c',
    appId: '1:1038997808447:android:846e82cbc665e328e61f8a',
    messagingSenderId: '1038997808447',
    projectId: 'venture-vault-4f892',
    storageBucket: 'venture-vault-4f892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4fwomodVnCZS8ZrtolQMiI4LsPt4t7LU',
    appId: '1:1038997808447:ios:fc673bc549123a6ee61f8a',
    messagingSenderId: '1038997808447',
    projectId: 'venture-vault-4f892',
    storageBucket: 'venture-vault-4f892.firebasestorage.app',
    iosBundleId: 'com.example.ventureVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4fwomodVnCZS8ZrtolQMiI4LsPt4t7LU',
    appId: '1:1038997808447:ios:fc673bc549123a6ee61f8a',
    messagingSenderId: '1038997808447',
    projectId: 'venture-vault-4f892',
    storageBucket: 'venture-vault-4f892.firebasestorage.app',
    iosBundleId: 'com.example.ventureVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EjhDrt7EUNTrueeIhGhGz7Md0t8kDAE',
    appId: '1:1038997808447:web:adc9ce3f6bfe5e78e61f8a',
    messagingSenderId: '1038997808447',
    projectId: 'venture-vault-4f892',
    authDomain: 'venture-vault-4f892.firebaseapp.com',
    storageBucket: 'venture-vault-4f892.firebasestorage.app',
    measurementId: 'G-QMY8LJXGL3',
  );
}
